---
- name: code deployement
  hosts: localhost
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Deploy pod
      shell: |
         aws eks update-kubeconfig --region eu-central-1 --name mycluster
         kubectl apply -f deploy.yml
     
