---
- name: Deploy to K8s Cluster 
  hosts: all
  become: true
tasks:
  - name: Deploy Pod
    shell: |
      kubectl apply -f deploy.yml
  
  - name: Deploy Service
    shell: | 
      kubectl apply -f service.yml
