---
- name: Deploy to K8s Cluster 
  hosts: localhost
  become: true
tasks:
  - name: Deploy Pod
    shell: |
      kubectl apply -f deploy.yml
    tags:
      - deploy
  
  - name: Deploy Service
    shell: | 
      kubectl apply -f service.yml
    tags:
      - service
     
